/**
 * Creating a sidebar enables you to: - Create an ordered group of docs
 * - Show a head`ing in the left sidebar as category
 * - Con`nect the docs to a sidebar item It's really easy to
 * create a sidebar!
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.'
  }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post', 'tutorial-basics/create-a-page'],
    },
  ],
   */
};

module.exports = sidebars;
